const unit11 = [
    { term: 'acquaintance', transcr: '/əˈkweɪntəns/', translation: 'знакомый' },
    { term: 'afford', transcr: '/əˈfɔːd/', translation: 'позволить себе' },
    { term: 'agitated', transcr: '/ˈædʒɪteɪtɪd/', translation: 'возбужденный' },
    { term: 'anniversary', transcr: '/ˌænɪˈvɜːsəri/', translation: 'годовщина' },
    { term: 'apparently', transcr: '/əˈpærəntli/', translation: 'очевидно' },
    { term: 'available', transcr: '/əˈveɪləbl/', translation: 'доступный' },
    { term: 'battery', transcr: '/ˈbætəri/', translation: 'батарея' },
    { term: 'bird-brained', transcr: '/ˈbɜːdbreɪnd/', translation: 'глупый' },
    { term: 'break out of', transcr: '/breɪk aʊt əv/', translation: 'вырваться из' },
    { term: 'break up', transcr: '/breɪk ʌp/', translation: 'расстаться' },
    { term: 'bruise', transcr: '/bruːz/', translation: 'синяк' },
    { term: 'burgle', transcr: '/ˈbɜːɡl/', translation: 'ограбить' },
    { term: 'candlestick', transcr: '/ˈkændlstɪk/', translation: 'подсвечник' },
    { term: 'cheers', transcr: '/tʃɪəz/', translation: 'ура' },
    { term: 'chimpanzee', transcr: '/ˌtʃɪmpænˈziː/', translation: 'шимпанзе' },
    { term: 'club together', transcr: '/klʌb təˈɡeðə(r)/', translation: 'скинуться' },
    { term: 'clue', transcr: '/kluː/', translation: 'улика' },
    { term: 'come up with', transcr: '/kʌm ʌp wɪð/', translation: 'придумать' },
    { term: 'cricket', transcr: '/ˈkrɪkɪt/', translation: 'крикет' },
    { term: 'crow', transcr: '/krəʊ/', translation: 'ворона' },
    { term: 'culprit', transcr: '/ˈkʌlprɪt/', translation: 'преступник' },
    { term: 'dehydrate', transcr: '/ˌdiːhaɪˈdreɪt/', translation: 'обезвоживать' },
    { term: 'dot', transcr: '/dɒt/', translation: 'точка' },
    { term: 'dreadful', transcr: '/ˈdredfl/', translation: 'ужасный' },
    { term: 'dump', transcr: '/dʌmp/', translation: 'сваливать' },
    { term: 'eat out', transcr: '/iːt aʊt/', translation: 'есть вне дома' },
    { term: 'eat up', transcr: '/iːt ʌp/', translation: 'съесть' },
    { term: 'elementary', transcr: '/ˌelɪˈmentri/', translation: 'элементарный' },
    { term: 'eyesight', transcr: '/ˈaɪsaɪt/', translation: 'зрение' },
    { term: 'fall out', transcr: '/fɔːl aʊt/', translation: 'ссориться' },
    { term: 'feather', transcr: '/ˈfeðə(r)/', translation: 'перо' },
    { term: 'gamble', transcr: '/ˈɡæmbl/', translation: 'играть в азартные игры' },
    { term: 'have around', transcr: '/hæv əˈraʊnd/', translation: 'иметь под рукой' },
    { term: 'hopefully', transcr: '/ˈhəʊpfəli/', translation: 'с надеждой' },
    { term: 'hurriedly', transcr: '/ˈhʌrɪdli/', translation: 'поспешно' },
    { term: 'identical', transcr: '/aɪˈdentɪkl/', translation: 'идентичный' },
    { term: 'impatiently', transcr: '/ɪmˈpeɪʃntli/', translation: 'нетерпеливо' },
    { term: 'intruder', transcr: '/ɪnˈtruːdə(r)/', translation: 'нарушитель' },
    { term: 'investigation', transcr: '/ɪnˌvestɪˈɡeɪʃn/', translation: 'расследование' },
    { term: 'irritably', transcr: '/ˈɪrɪtəbli/', translation: 'раздраженно' },
    { term: 'jelly', transcr: '/ˈdʒeli/', translation: 'желе' },
    { term: 'lecture', transcr: '/ˈlektʃə(r)/', translation: 'лекция' },
    { term: 'liar', transcr: '/ˈlaɪə(r)/', translation: 'лжец' },
    { term: 'lightning', transcr: '/ˈlaɪtnɪŋ/', translation: 'молния' },
    { term: 'lightning conductor', transcr: '/ˈlaɪtnɪŋ kənˈdʌktə(r)/', translation: 'громоотвод' },
    { term: 'long jump', transcr: '/lɒŋ dʒʌmp/', translation: 'прыжок в длину' },
    { term: 'look like', transcr: '/lʊk laɪk/', translation: 'выглядеть как' },
    { term: 'lottery', transcr: '/ˈlɒtəri/', translation: 'лотерея' },
    { term: 'lump', transcr: '/lʌmp/', translation: 'кусок' },
    { term: 'make sth up', transcr: '/meɪk ʌp/', translation: 'выдумывать' },
    { term: 'make up (w sb)', transcr: '/meɪk ʌp/', translation: 'мириться' },
    { term: 'mimic', transcr: '/ˈmɪmɪk/', translation: 'подражать' },
    { term: 'mineral water', transcr: '/ˈmɪnərəl ˈwɔːtə(r)/', translation: 'минеральная вода' },
    { term: 'motive', transcr: '/ˈməʊtɪv/', translation: 'мотив' },
    { term: 'naturally', transcr: '/ˈnætʃrəli/', translation: 'естественно' },
    { term: 'No kidding!', transcr: '/nəʊ ˈkɪdɪŋ/', translation: 'без шуток' },
    { term: 'obviously', transcr: '/ˈɒbviəsli/', translation: 'очевидно' },
    { term: 'on tiptoe', transcr: '/ɒn ˈtɪptəʊ/', translation: 'на цыпочках' },
    { term: 'optical illusion', transcr: '/ˈɒptɪkl ɪˈluːʒn/', translation: 'оптическая иллюзия' },
    { term: 'oversleep', transcr: '/ˌəʊvəˈsliːp/', translation: 'проспать' },
    { term: 'parrot', transcr: '/ˈpærət/', translation: 'попугай' },
    { term: 'personally', transcr: '/ˈpɜːsənəli/', translation: 'лично' },
    { term: 'presumably', transcr: '/prɪˈzjuːməbli/', translation: 'предположительно' },
    { term: 'promote', transcr: '/prəˈməʊt/', translation: 'способствовать' },
    { term: 'radar', transcr: '/ˈreɪdɑː(r)/', translation: 'радар' },
    { term: 'ransack', transcr: '/ˈrænsæk/', translation: 'обыскивать' },
    { term: 'really', transcr: '/ˈrɪəli/', translation: 'действительно' },
    { term: 'reflect', transcr: '/rɪˈflekt/', translation: 'отражать' },
    { term: 'refuse', transcr: '/rɪˈfjuːz/', translation: 'отказываться' },
    { term: 'responsible', transcr: '/rɪˈspɒnsəbl/', translation: 'ответственный' },
    { term: 'rugby', transcr: '/ˈrʌɡbi/', translation: 'регби' },
    { term: 'save up', transcr: '/seɪv ʌp/', translation: 'копить' },
    { term: 'scandal', transcr: '/ˈskændl/', translation: 'скандал' },
    { term: 'shrink', transcr: '/ʃrɪŋk/', translation: 'сжиматься' },
    { term: 'skyscraper', transcr: '/ˈskaɪskreɪpə(r)/', translation: 'небоскреб' },
    { term: 'snowflake', transcr: '/ˈsnəʊfleɪk/', translation: 'снежинка' },
    { term: 'sole', transcr: '/səʊl/', translation: 'подошва' },
    { term: 'solve', transcr: '/sɒlv/', translation: 'решать' },
    { term: 'sort out', transcr: '/sɔːt aʊt/', translation: 'разбираться' },
    { term: 'spare', transcr: '/speə(r)/', translation: 'запасной' },
    { term: 'spike', transcr: '/spaɪk/', translation: 'шип' },
    { term: 'strike', transcr: '/straɪk/', translation: 'ударять' },
    { term: 'suspicious', transcr: '/səˈspɪʃəs/', translation: 'подозрительный' },
    { term: 'take up', transcr: '/teɪk ʌp/', translation: 'заниматься' },
    { term: 'threshold', transcr: '/ˈθreʃhəʊld/', translation: 'порог' },
    { term: 'tidy up', transcr: '/ˈtaɪdi ʌp/', translation: 'убирать' },
    { term: 'to be honest', transcr: '/tə bi ˈɒnɪst/', translation: 'честно говоря' },
    { term: 'translation', transcr: '/trænzˈleɪʃn/', translation: 'перевод' },
    { term: 'trick', transcr: '/trɪk/', translation: 'трюк' },
    { term: 'tutor', transcr: '/ˈtjuːtə(r)/', translation: 'репетитор' },
    { term: 'undoubtedly', transcr: '/ʌnˈdaʊtɪdli/', translation: 'несомненно' },
    { term: 'unplug', transcr: '/ˌʌnˈplʌɡ/', translation: 'отключать' },
    { term: 'work out', transcr: '/wɜːk aʊt/', translation: 'разрабатывать' },
    { term: 'work sth out', transcr: '/wɜːk aʊt/', translation: 'разобраться' },
    { term: 'wobbly', transcr: '/ˈwɒbli/', translation: 'шаткий' },
    { term: 'zillions', transcr: '/ˈzɪliənz/', translation: 'миллионы' }
];
