const unit10 = [
    { term: 'amenity', transcr: '/əˈmiːnəti/', translation: 'удобство' },
    { term: 'ancestor', transcr: '/ˈænsestər/', translation: 'предок' },
    { term: 'appear', transcr: '/əˈpɪər/', translation: 'появляться' },
    { term: 'arch', transcr: '/ɑːrtʃ/', translation: 'арка' },
    { term: 'basically', transcr: '/ˈbeɪsɪkli/', translation: 'в основном' },
    { term: 'brewery', transcr: '/ˈbruːəri/', translation: 'пивоварня' },
    { term: 'bronze', transcr: '/brɒnz/', translation: 'бронза' },
    { term: 'burger', transcr: '/ˈbɜːrɡər/', translation: 'бургер' },
    { term: 'calculation', transcr: '/ˌkælkjuˈleɪʃən/', translation: 'расчет' },
    { term: 'capacity', transcr: '/kəˈpæsəti/', translation: 'вместимость' },
    { term: 'censorship', transcr: '/ˈsensərʃɪp/', translation: 'цензура' },
    { term: 'chairman', transcr: '/ˈtʃɛərmən/', translation: 'председатель' },
    { term: 'coal', transcr: '/koʊl/', translation: 'уголь' },
    { term: 'code', transcr: '/koʊd/', translation: 'код' },
    { term: 'commerce', transcr: '/ˈkɒmɜːrs/', translation: 'торговля' },
    { term: 'complex', transcr: '/ˈkɒmpleks/', translation: 'сложный' },
    { term: 'crystal', transcr: '/ˈkrɪstəl/', translation: 'кристалл' },
    { term: 'daily', transcr: '/ˈdeɪli/', translation: 'ежедневный' },
    { term: 'decoration', transcr: '/ˌdekəˈreɪʃən/', translation: 'украшение' },
    { term: 'democracy', transcr: '/dɪˈmɒkrəsi/', translation: 'демократия' },
    { term: 'depict', transcr: '/dɪˈpɪkt/', translation: 'изображать' },
    { term: 'device', transcr: '/dɪˈvaɪs/', translation: 'устройство' },
    { term: 'diagnose', transcr: '/ˌdaɪəɡˈnoʊz/', translation: 'диагностировать' },
    { term: 'digital', transcr: '/ˈdɪdʒɪtəl/', translation: 'цифровой' },
    { term: 'distinctive', transcr: '/dɪˈstɪŋktɪv/', translation: 'отличительный' },
    { term: 'district', transcr: '/ˈdɪstrɪkt/', translation: 'район' },
    { term: 'efficient', transcr: '/ɪˈfɪʃənt/', translation: 'эффективный' },
    { term: 'embrace', transcr: '/ɪmˈbreɪs/', translation: 'охватывать' },
    { term: 'error', transcr: '/ˈerər/', translation: 'ошибка' },
    { term: 'estate agent', transcr: '/ɪˈsteɪt ˌeɪdʒənt/', translation: 'агент по недвижимости' },
    { term: 'ethnic group', transcr: '/ˈeθnɪk ɡruːp/', translation: 'этническая группа' },
    { term: 'facilities', transcr: '/fəˈsɪlətiz/', translation: 'удобства' },
    { term: 'feat', transcr: '/fiːt/', translation: 'подвиг' },
    { term: 'feature', transcr: '/ˈfiːtʃər/', translation: 'особенность' },
    { term: 'flash', transcr: '/flæʃ/', translation: 'вспышка' },
    { term: 'float', transcr: '/floʊt/', translation: 'плавать' },
    { term: 'found', transcr: '/faʊnd/', translation: 'основывать' },
    { term: 'gig', transcr: '/ɡɪɡ/', translation: 'концерт' },
    { term: 'glide', transcr: '/ɡlaɪd/', translation: 'скользить' },
    { term: 'Gothic', transcr: '/ˈɡɒθɪk/', translation: 'готический' },
    { term: 'haircut', transcr: '/ˈhɛərkʌt/', translation: 'стрижка' },
    { term: 'halt', transcr: '/hɔːlt/', translation: 'останавливать' },
    { term: 'handcuffs', transcr: '/ˈhændkʌfs/', translation: 'наручники' },
    { term: 'headlight', transcr: '/ˈhedlaɪt/', translation: 'фара' },
    { term: 'headphones', transcr: '/ˈhedfoʊnz/', translation: 'наушники' },
    { term: 'headquarters', transcr: '/ˈhedkwɔːrtərz/', translation: 'штаб-квартира' },
    { term: 'headstone', transcr: '/ˈhedstoʊn/', translation: 'надгробие' },
    { term: 'headway', transcr: '/ˈhedweɪ/', translation: 'прогресс' },
    { term: 'high tech', transcr: '/haɪ tek/', translation: 'высокие технологии' },
    { term: 'home-made', transcr: '/ˌhoʊmˈmeɪd/', translation: 'домашнего изготовления' },
    { term: 'influence', transcr: '/ˈɪnfluəns/', translation: 'влияние' },
    { term: 'inner-city', transcr: '/ˌɪnərˈsɪti/', translation: 'внутренний город' },
    { term: 'instantly', transcr: '/ˈɪnstəntli/', translation: 'мгновенно' },
    { term: 'laundry', transcr: '/ˈlɔːndri/', translation: 'прачечная' },
    { term: 'log onto', transcr: '/lɒɡ ˈɒntuː/', translation: 'войти в систему' },
    { term: 'major', transcr: '/ˈmeɪdʒər/', translation: 'главный' },
    { term: 'motorbike', transcr: '/ˈmoʊtərbaɪk/', translation: 'мотоцикл' },
    { term: 'motorway', transcr: '/ˈmoʊtərweɪ/', translation: 'автомагистраль' },
    { term: 'mouth (of a river)', transcr: '/maʊθ əv ə ˈrɪvər/', translation: 'устье (реки)' },
    { term: 'net', transcr: '/net/', translation: 'сеть' },
    { term: 'newsagent', transcr: '/ˈnuːzeɪdʒənt/', translation: 'газетный киоск' },
    { term: 'nickname', transcr: '/ˈnɪkneɪm/', translation: 'прозвище' },
    { term: 'notice board', transcr: '/ˈnoʊtɪsbɔːrd/', translation: 'доска объявлений' },
    { term: 'online dating', transcr: '/ˈɒnlaɪn ˈdeɪtɪŋ/', translation: 'онлайн-знакомства' },
    { term: 'onscreen', transcr: '/ˈɒnskriːn/', translation: 'на экране' },
    { term: 'operate', transcr: '/ˈɒpəreɪt/', translation: 'управлять' },
    { term: 'outdated', transcr: '/ˌaʊtˈdeɪtɪd/', translation: 'устаревший' },
    { term: 'penthouse', transcr: '/ˈpenthaʊs/', translation: 'пентхаус' },
    { term: 'perfectly', transcr: '/ˈpɜːrfɪktli/', translation: 'идеально' },
    { term: 'plumbing', transcr: '/ˈplʌmɪŋ/', translation: 'водопровод' },
    { term: 'poster', transcr: '/ˈpoʊstər/', translation: 'плакат' },
    { term: 'print', transcr: '/prɪnt/', translation: 'печатать' },
    { term: 'programmable', transcr: '/ˈproʊɡræməbəl/', translation: 'программируемый' },
    { term: 'regeneration', transcr: '/rɪˌdʒenəˈreɪʃən/', translation: 'регенерация' },
    { term: 'remote', transcr: '/rɪˈmoʊt/', translation: 'удаленный' },
    { term: 'restoration', transcr: '/ˌrestəˈreɪʃən/', translation: 'реставрация' },
    { term: 'revolving door', transcr: '/rɪˈvɒlvɪŋ dɔːr/', translation: 'вращающаяся дверь' },
    { term: 'satellite navigation', transcr: '/ˈsætəlaɪt ˌnævɪˈɡeɪʃən/', translation: 'спутниковая навигация' },
    { term: 'sharp', transcr: '/ʃɑːrp/', translation: 'острый' },
    { term: 'silicon', transcr: '/ˈsɪlɪkən/', translation: 'кремний' },
    { term: 'skateboarding', transcr: '/ˈskeɪtbɔːrdɪŋ/', translation: 'скейтбординг' },
    { term: 'skyline', transcr: '/ˈskaɪlaɪn/', translation: 'линия горизонта' },
    { term: 'social networking', transcr: '/ˈsoʊʃəl ˈnetwɜːrkɪŋ/', translation: 'социальные сети' },
    { term: 'span', transcr: '/spæn/', translation: 'промежуток' },
    { term: 'statue', transcr: '/ˈstætʃuː/', translation: 'статуя' },
    { term: 'stick', transcr: '/stɪk/', translation: 'палка' },
    { term: 'sticky', transcr: '/ˈstɪki/', translation: 'липкий' },
    { term: 'storage', transcr: '/ˈstɔːrɪdʒ/', translation: 'хранилище' },
    { term: 'supply', transcr: '/səˈplaɪ/', translation: 'поставлять' },
    { term: 'surface', transcr: '/ˈsɜːrfɪs/', translation: 'поверхность' },
    { term: 'surgeon', transcr: '/ˈsɜːrdʒən/', translation: 'хирург' },
    { term: 'switch', transcr: '/swɪtʃ/', translation: 'переключатель' },
    { term: 'thriving', transcr: '/ˈθraɪvɪŋ/', translation: 'процветающий' },
    { term: 'trace', transcr: '/treɪs/', translation: 'след' },
    { term: 'traffic jam', transcr: '/ˈtræfɪk dʒæm/', translation: 'пробка' },
    { term: 'traffic lights', transcr: '/ˈtræfɪk laɪts/', translation: 'светофор' },
    { term: 'traffic warden', transcr: '/ˈtræfɪk ˈwɔːrdn/', translation: 'инспектор дорожного движения' },
    { term: 'transfer', transcr: '/trænsˈfɜːr/', translation: 'переводить' },
    { term: 'transistor', transcr: '/trænˈzɪstər/', translation: 'транзистор' },
    { term: 'treat', transcr: '/triːt/', translation: 'лечить' },
    { term: 'triumph', transcr: '/ˈtraɪʌmf/', translation: 'триумф' },
    { term: 'tube', transcr: '/tuːb/', translation: 'труба' },
    { term: 'undivided', transcr: '/ˌʌndɪˈvaɪdɪd/', translation: 'неделимый' },
    { term: 'unsupported', transcr: '/ˌʌnsəˈpɔːrtɪd/', translation: 'неподдерживаемый' },
    { term: 'waiting room', transcr: '/ˈweɪtɪŋ ruːm/', translation: 'зал ожидания' },
    { term: 'wallpaper', transcr: '/ˈwɔːlpeɪpər/', translation: 'обои' },
    { term: 'wool', transcr: '/wʊl/', translation: 'шерсть' },
    { term: 'wrapping paper', transcr: '/ˈræpɪŋ ˌpeɪpər/', translation: 'оберточная бумага' }
];
