const unit8 = [
    { term: 'approach', transcr: '/əˈproʊtʃ/', translation: 'подход' },
    { term: 'ascent', transcr: '/əˈsɛnt/', translation: 'восхождение' },
    { term: 'base', transcr: '/beɪs/', translation: 'база' },
    { term: 'battle', transcr: '/ˈbætəl/', translation: 'битва' },
    { term: 'bite', transcr: '/baɪt/', translation: 'кусать' },
    { term: 'blow', transcr: '/bloʊ/', translation: 'дуть' },
    { term: 'blow up', transcr: '/bloʊ ʌp/', translation: 'взрывать' },
    { term: 'body language', transcr: '/ˈbɒdi ˈlæŋɡwɪdʒ/', translation: 'язык тела' },
    { term: 'bold', transcr: '/boʊld/', translation: 'смелый' },
    { term: 'bunk bed', transcr: '/bʌŋk bɛd/', translation: 'двухъярусная кровать' },
    { term: 'canoe', transcr: '/kəˈnuː/', translation: 'каноэ' },
    { term: 'catapult', transcr: '/ˈkætəpʌlt/', translation: 'катапульта' },
    { term: 'clap', transcr: '/klæp/', translation: 'хлопать' },
    { term: 'cliff', transcr: '/klɪf/', translation: 'утес' },
    { term: 'conquer', transcr: '/ˈkɒŋkər/', translation: 'покорять' },
    { term: 'crew', transcr: '/kruː/', translation: 'экипаж' },
    { term: 'cross', transcr: '/krɒs/', translation: 'пересекать' },
    { term: 'crossing', transcr: '/ˈkrɒsɪŋ/', translation: 'переправа' },
    { term: 'cure', transcr: '/kjʊər/', translation: 'лечить' },
    { term: 'dare', transcr: '/dɛər/', translation: 'осмеливаться' },
    { term: 'daring', transcr: '/ˈdɛərɪŋ/', translation: 'смелый' },
    { term: 'declare', transcr: '/dɪˈklɛər/', translation: 'объявлять' },
    { term: 'defeat', transcr: '/dɪˈfiːt/', translation: 'поражение' },
    { term: 'DIY', transcr: '/ˌdiː aɪ ˈwaɪ/', translation: 'сделай сам' },
    { term: 'DNA', transcr: '/ˌdiː ɛn ˈeɪ/', translation: 'ДНК' },
    { term: 'empire', transcr: '/ˈɛmpaɪər/', translation: 'империя' },
    { term: 'face', transcr: '/feɪs/', translation: 'лицо' },
    { term: 'fearless', transcr: '/ˈfɪərləs/', translation: 'бесстрашный' },
    { term: 'ferry', transcr: '/ˈfɛri/', translation: 'паром' },
    { term: 'fighter', transcr: '/ˈfaɪtər/', translation: 'боец' },
    { term: 'force', transcr: '/fɔːrs/', translation: 'сила' },
    { term: 'found', transcr: '/faʊnd/', translation: 'основывать' },
    { term: 'freak out', transcr: '/friːk aʊt/', translation: 'психовать' },
    { term: 'gene', transcr: '/dʒiːn/', translation: 'ген' },
    { term: 'get out of hand', transcr: '/ɡɛt aʊt əv hænd/', translation: 'выйти из-под контроля' },
    { term: 'go over someone’s head', transcr: '/ɡoʊ ˈoʊvər ˈsʌmwʌnz hɛd/', translation: 'быть выше чьего-либо понимания' },
    { term: 'have a sweet tooth', transcr: '/hæv ə swiːt tuːθ/', translation: 'быть сладкоежкой' },
    { term: 'hit a problem', transcr: '/hɪt ə ˈprɒbləm/', translation: 'столкнуться с проблемой' },
    { term: 'hollow', transcr: '/ˈhɒloʊ/', translation: 'пустой' },
    { term: 'hug', transcr: '/hʌɡ/', translation: 'обнимать' },
    { term: 'iceberg', transcr: '/ˈaɪsbɜːrɡ/', translation: 'айсберг' },
    { term: 'illiterate', transcr: '/ɪˈlɪtərət/', translation: 'неграмотный' },
    { term: 'infection', transcr: '/ɪnˈfɛkʃən/', translation: 'инфекция' },
    { term: 'initially', transcr: '/ɪˈnɪʃəli/', translation: 'изначально' },
    { term: 'innocent', transcr: '/ˈɪnəsənt/', translation: 'невинный' },
    { term: 'install', transcr: '/ɪnˈstɔːl/', translation: 'устанавливать' },
    { term: 'kick', transcr: '/kɪk/', translation: 'пинать' },
    { term: 'kick up a fuss', transcr: '/kɪk ʌp ə fʌs/', translation: 'поднять шум' },
    { term: 'kneel', transcr: '/niːl/', translation: 'становиться на колени' },
    { term: 'lack', transcr: '/læk/', translation: 'недостаток' },
    { term: 'ladder', transcr: '/ˈlædər/', translation: 'лестница' },
    { term: 'leadership', transcr: '/ˈliːdərʃɪp/', translation: 'лидерство' },
    { term: 'lick', transcr: '/lɪk/', translation: 'лизать' },
    { term: 'lifeboats', transcr: '/ˈlaɪfboʊts/', translation: 'спасательные шлюпки' },
    { term: 'lower', transcr: '/ˈloʊər/', translation: 'опускать' },
    { term: 'maiden voyage', transcr: '/ˈmeɪdən ˈvɔɪɪdʒ/', translation: 'первое плавание' },
    { term: 'manpower', transcr: '/ˈmænpaʊər/', translation: 'рабочая сила' },
    { term: 'military', transcr: '/ˈmɪlətɛri/', translation: 'военный' },
    { term: 'nail', transcr: '/neɪl/', translation: 'гвоздь' },
    { term: 'numerous', transcr: '/ˈnuːmərəs/', translation: 'многочисленный' },
    { term: 'overcome', transcr: '/ˌoʊvərˈkʌm/', translation: 'преодолевать' },
    { term: 'overweight', transcr: '/ˌoʊvərˈweɪt/', translation: 'избыточный вес' },
    { term: 'oxygen', transcr: '/ˈɒksɪdʒən/', translation: 'кислород' },
    { term: 'oyster', transcr: '/ˈɔɪstər/', translation: 'устрица' },
    { term: 'panic', transcr: '/ˈpænɪk/', translation: 'паника' },
    { term: 'pass', transcr: '/pæs/', translation: 'проходить' },
    { term: 'perish', transcr: '/ˈpɛrɪʃ/', translation: 'гибнуть' },
    { term: 'phobia', transcr: '/ˈfoʊbiə/', translation: 'фобия' },
    { term: 'pitch-black', transcr: '/pɪtʃ blæk/', translation: 'черный как смоль' },
    { term: 'playground', transcr: '/ˈpleɪɡraʊnd/', translation: 'детская площадка' },
    { term: 'poisonous', transcr: '/ˈpɔɪzənəs/', translation: 'ядовитый' },
    { term: 'pray', transcr: '/preɪ/', translation: 'молиться' },
    { term: 'program', transcr: '/ˈproʊɡræm/', translation: 'программа' },
    { term: 'prosperous', transcr: '/ˈprɒspərəs/', translation: 'процветающий' },
    { term: 'province', transcr: '/ˈprɒvɪns/', translation: 'провинция' },
    { term: 'psychotherapist', transcr: '/ˌsaɪkoʊˈθɛrəpɪst/', translation: 'психотерапевт' },
    { term: 'pull someone’s leg', transcr: '/pʊl ˈsʌmwʌnz lɛɡ/', translation: 'морочить голову' },
    { term: 'put up', transcr: '/pʊt ʌp/', translation: 'мириться' },
    { term: 'raft', transcr: '/ræft/', translation: 'плот' },
    { term: 'recognize', transcr: '/ˈrɛkəɡnaɪz/', translation: 'узнавать' },
    { term: 'reduce', transcr: '/rɪˈduːs/', translation: 'уменьшать' },
    { term: 'remain', transcr: '/rɪˈmeɪn/', translation: 'оставаться' },
    { term: 'remarkable', transcr: '/rɪˈmɑːrkəbəl/', translation: 'замечательный' },
    { term: 'remote', transcr: '/rɪˈmoʊt/', translation: 'удаленный' },
    { term: 'revolutionary', transcr: '/ˌrɛvəˈluːʃəˌnɛri/', translation: 'революционный' },
    { term: 'rule', transcr: '/ruːl/', translation: 'править' },
    { term: 'scar', transcr: '/skɑːr/', translation: 'шрам' },
    { term: 'scratch', transcr: '/skrætʃ/', translation: 'царапать' },
    { term: 'see eye to eye', transcr: '/siː aɪ tu aɪ/', translation: 'сходиться во взглядах' },
    { term: 'set off', transcr: '/sɛt ɔːf/', translation: 'отправляться' },
    { term: 'sickness', transcr: '/ˈsɪknəs/', translation: 'болезнь' },
    { term: 'silly', transcr: '/ˈsɪli/', translation: 'глупый' },
    { term: 'slide', transcr: '/slaɪd/', translation: 'скользить' },
    { term: 'slip', transcr: '/slɪp/', translation: 'поскользнуться' },
    { term: 'snorkel', transcr: '/ˈsnɔːrkəl/', translation: 'трубка для плавания' },
    { term: 'soldier', transcr: '/ˈsoʊldʒər/', translation: 'солдат' },
    { term: 'stack', transcr: '/stæk/', translation: 'стопка' },
    { term: 'stare', transcr: '/stɛər/', translation: 'пялиться' },
    { term: 'steerage', transcr: '/ˈstɪərɪdʒ/', translation: 'третий класс' },
    { term: 'struggle', transcr: '/ˈstrʌɡəl/', translation: 'борьба' },
    { term: 'suffer', transcr: '/ˈsʌfər/', translation: 'страдать' },
    { term: 'sumptuous', transcr: '/ˈsʌmptʃuəs/', translation: 'роскошный' },
    { term: 'superior', transcr: '/suːˈpɪəriər/', translation: 'превосходный' },
    { term: 'swallow', transcr: '/ˈswɒloʊ/', translation: 'глотать' },
    { term: 'sweaty', transcr: '/ˈswɛti/', translation: 'потный' },
    { term: 'symptom', transcr: '/ˈsɪmptəm/', translation: 'симптом' },
    { term: 'tear down', transcr: '/tɛər daʊn/', translation: 'сносить' },
    { term: 'terrified', transcr: '/ˈtɛrəfaɪd/', translation: 'в ужасе' },
    { term: 'terror', transcr: '/ˈtɛrər/', translation: 'террор' },
    { term: 'threaten', transcr: '/ˈθrɛtən/', translation: 'угрожать' },
    { term: 'trek', transcr: '/trɛk/', translation: 'поход' },
    { term: 'tribesmen', transcr: '/ˈtraɪbzmən/', translation: 'соплеменники' },
    { term: 'tune', transcr: '/tuːn/', translation: 'мелодия' },
    { term: 'unbelievable', transcr: '/ˌʌnbɪˈliːvəbəl/', translation: 'невероятный' },
    { term: 'unsinkable', transcr: '/ʌnˈsɪŋkəbəl/', translation: 'непотопляемый' },
    { term: 'waste your breath', transcr: '/weɪst jʊər brɛθ/', translation: 'тратить слова попусту' },
    { term: 'whistle', transcr: '/ˈwɪsəl/', translation: 'свистеть' }
];
