const unit9 = [
    { term: 'action-packed', transcr: '/ˈækʃən pækt/', translation: 'насыщенный событиями' },
    { term: 'addict', transcr: '/ˈædɪkt/', translation: 'наркоман' },
    { term: 'ages', transcr: '/ˈeɪdʒɪz/', translation: 'вечность' },
    { term: 'arrest', transcr: '/əˈrest/', translation: 'арест' },
    { term: 'ashamed', transcr: '/əˈʃeɪmd/', translation: 'пристыженный' },
    { term: 'balance', transcr: '/ˈbæləns/', translation: 'баланс' },
    { term: 'bear with', transcr: '/beə wɪð/', translation: 'мириться с' },
    { term: 'blood', transcr: '/blʌd/', translation: 'кровь' },
    { term: 'bother', transcr: '/ˈbɒðə(r)/', translation: 'беспокоить' },
    { term: 'brainstorm', transcr: '/ˈbreɪnstɔːm/', translation: 'мозговой штурм' },
    { term: 'buddy', transcr: '/ˈbʌdi/', translation: 'приятель' },
    { term: 'bully', transcr: '/ˈbʊli/', translation: 'хулиган' },
    { term: 'bump into', transcr: '/bʌmp ˈɪntu/', translation: 'столкнуться' },
    { term: 'burglary', transcr: '/ˈbɜːɡləri/', translation: 'кража со взломом' },
    { term: 'clean up', transcr: '/kliːn ʌp/', translation: 'убираться' },
    { term: 'clear', transcr: '/klɪə(r)/', translation: 'ясный' },
    { term: 'convict', transcr: '/kənˈvɪkt/', translation: 'осужденный' },
    { term: 'counsellor', transcr: '/ˈkaʊnsələ(r)/', translation: 'консультант' },
    { term: 'curious', transcr: '/ˈkjʊəriəs/', translation: 'любопытный' },
    { term: 'determined', transcr: '/dɪˈtɜːmɪnd/', translation: 'решительный' },
    { term: 'digit', transcr: '/ˈdɪdʒɪt/', translation: 'цифра' },
    { term: 'dozen', transcr: '/ˈdʌzn/', translation: 'дюжина' },
    { term: 'dysfunctional', transcr: '/dɪsˈfʌŋkʃənl/', translation: 'дисфункциональный' },
    { term: 'economize', transcr: '/ɪˈkɒnəmaɪz/', translation: 'экономить' },
    { term: 'effective', transcr: '/ɪˈfektɪv/', translation: 'эффективный' },
    { term: 'eldest', transcr: '/ˈeldɪst/', translation: 'самый старший' },
    { term: 'encounter', transcr: '/ɪnˈkaʊntə(r)/', translation: 'столкновение' },
    { term: 'enter', transcr: '/ˈentə(r)/', translation: 'входить' },
    { term: 'explode', transcr: '/ɪkˈspləʊd/', translation: 'взрываться' },
    { term: 'faceless', transcr: '/ˈfeɪsləs/', translation: 'безликий' },
    { term: 'find fault', transcr: '/faɪnd fɔːlt/', translation: 'придираться' },
    { term: 'fraud', transcr: '/frɔːd/', translation: 'мошенничество' },
    { term: 'get through to', transcr: '/ɡet θruː tu/', translation: 'дозвониться' },
    { term: 'grin', transcr: '/ɡrɪn/', translation: 'ухмылка' },
    { term: 'gym', transcr: '/dʒɪm/', translation: 'спортзал' },
    { term: 'hand over', transcr: '/hænd ˈəʊvə(r)/', translation: 'передавать' },
    { term: 'head teacher', transcr: '/hed ˈtiːtʃə(r)/', translation: 'завуч' },
    { term: 'heroin', transcr: '/ˈherəʊɪn/', translation: 'героин' },
    { term: 'hit rock bottom', transcr: '/hɪt rɒk ˈbɒtəm/', translation: 'достичь дна' },
    { term: 'homeless', transcr: '/ˈhəʊmləs/', translation: 'бездомный' },
    { term: 'imprisonment', transcr: '/ɪmˈprɪznmənt/', translation: 'тюремное заключение' },
    { term: 'in touch', transcr: '/ɪn tʌtʃ/', translation: 'на связи' },
    { term: 'jail', transcr: '/dʒeɪl/', translation: 'тюрьма' },
    { term: 'knock over', transcr: '/nɒk ˈəʊvə(r)/', translation: 'опрокинуть' },
    { term: 'letter box', transcr: '/ˈletə bɒks/', translation: 'почтовый ящик' },
    { term: 'light', transcr: '/laɪt/', translation: 'свет' },
    { term: 'limit', transcr: '/ˈlɪmɪt/', translation: 'предел' },
    { term: 'litter bin', transcr: '/ˈlɪtə bɪn/', translation: 'мусорное ведро' },
    { term: 'locate', transcr: '/ləʊˈkeɪt/', translation: 'определить местоположение' },
    { term: 'make a scene', transcr: '/meɪk ə siːn/', translation: 'устроить сцену' },
    { term: 'mind your own business', transcr: '/maɪnd jɔːr əʊn ˈbɪznəs/', translation: 'не лезь не в свое дело' },
    { term: 'ordinary', transcr: '/ˈɔːdnri/', translation: 'обычный' },
    { term: 'outburst', transcr: '/ˈaʊtbɜːst/', translation: 'вспышка' },
    { term: 'over the moon', transcr: '/ˈəʊvə ðə muːn/', translation: 'на седьмом небе от счастья' },
    { term: 'overdrawn', transcr: '/ˌəʊvəˈdrɔːn/', translation: 'превысивший кредит' },
    { term: 'passer-by', transcr: '/ˌpɑːsə ˈbaɪ/', translation: 'прохожий' },
    { term: 'penniless', transcr: '/ˈpeniləs/', translation: 'без гроша' },
    { term: 'phone in', transcr: '/fəʊn ɪn/', translation: 'позвонить' },
    { term: 'play truant', transcr: '/pleɪ ˈtruːənt/', translation: 'прогуливать' },
    { term: 'prison', transcr: '/ˈprɪzn/', translation: 'тюрьма' },
    { term: 'protect', transcr: '/prəˈtekt/', translation: 'защищать' },
    { term: 'punishment', transcr: '/ˈpʌnɪʃmənt/', translation: 'наказание' },
    { term: 'purpose', transcr: '/ˈpɜːpəs/', translation: 'цель' },
    { term: 'pursue', transcr: '/pəˈsjuː/', translation: 'преследовать' },
    { term: 'queue', transcr: '/kjuː/', translation: 'очередь' },
    { term: 'receipt', transcr: '/rɪˈsiːt/', translation: 'квитанция' },
    { term: 'register', transcr: '/ˈredʒɪstə(r)/', translation: 'регистр' },
    { term: 'rehabilitate', transcr: '/ˌriːəˈbɪlɪteɪt/', translation: 'восстанавливать' },
    { term: 'release', transcr: '/rɪˈliːs/', translation: 'освобождать' },
    { term: 'relieved', transcr: '/rɪˈliːvd/', translation: 'облегченный' },
    { term: 'restorative justice', transcr: '/rɪˈstɔːrətɪv ˈdʒʌstɪs/', translation: 'восстановительное правосудие' },
    { term: 'rude', transcr: '/ruːd/', translation: 'грубый' },
    { term: 'scruffy', transcr: '/ˈskrʌfi/', translation: 'неряшливый' },
    { term: 'shop-lift', transcr: '/ˈʃɒplɪft/', translation: 'красть в магазине' },
    { term: 'social worker', transcr: '/ˈsəʊʃl ˈwɜːkə(r)/', translation: 'соцработник' },
    { term: 'stitch', transcr: '/stɪtʃ/', translation: 'стежок' },
    { term: 'stop dead', transcr: '/stɒp ded/', translation: 'остановиться как вкопанный' },
    { term: 'storm off', transcr: '/stɔːm ɒf/', translation: 'уйти в гневе' },
    { term: 'stuff', transcr: '/stʌf/', translation: 'хлам' },
    { term: 'stunned', transcr: '/stʌnd/', translation: 'ошеломленный' },
    { term: 'suspect', transcr: '/səˈspekt/', translation: 'подозреваемый' },
    { term: 'temperature', transcr: '/ˈtemprətʃə(r)/', translation: 'температура' },
    { term: 'theft', transcr: '/θeft/', translation: 'кража' },
    { term: 'timid', transcr: '/ˈtɪmɪd/', translation: 'робкий' },
    { term: 'tremble', transcr: '/ˈtrembl/', translation: 'дрожать' },
    { term: 'urban', transcr: '/ˈɜːbən/', translation: 'городской' },
    { term: 'VAT', transcr: '/viː eɪ ˈtiː/', translation: 'НДС' },
    { term: 'victim', transcr: '/ˈvɪktɪm/', translation: 'жертва' },
    { term: 'violence', transcr: '/ˈvaɪələns/', translation: 'насилие' }
];
