window.textExtraPerformance = {
    id: 'textExtraPerformance',
    topic: 'Culture',
    titleEn: "PERFORMANCE CAPTURE",
    titleRu: "ЗАХВАТ ДВИЖЕНИЙ (Performance Capture)",
    contentEn: [
        "These days, we hardly think about 'special effects' in films - we're so used to them, they're not actually that special any more! There's the strange, half-human Gollum in The Lord of the Rings, the lifelike Incredible Hulk, and the blue-skinned Na'vi people in Avatar. These were all digitally created, but we believe in them as real characters, and forget the technical tricks involved. But how do they do it? The answer in most cases is Performance Capture.",
        "Performance Capture is a way of translating a real actor's performance into a digital character. Actors can perform naturally on a digital stage set, and this performance is then 'captured' by cameras and translated into an expressive digital character. If real actors are not involved, digital characters can often seem lifeless and dull.",
        "Tim Doubleday is a face specialist who has worked in Performance Capture for 12 years. He works for Europe's leading Performance Capture studio, Imaginarium, based in London. It was founded by the actor Andy Serkis and Jonathan Cavendish. Tim's role is facial supervisor. He's responsible for capturing the subtle movements in the actors' faces, which are used to produce lifelike facial expressions on digital characters.",
        "Tim tells the story of how the music video was made for the rock band Coldplay. Chris Martin of Coldplay met Andy Serkis on a plane, and they decided to do something together. We got the band members onto our studio set, which has about 50 cameras around it, all linked to a central computer.",
        "All performers wear skin-tight suits with reflective markers on them. Light from the cameras reflects back from the markers and is picked up by the computer, which records every movement. The performer's face is also covered with small marker dots and they wear a head-mounted camera to capture even tiny movements in the face.",
        "Andy Serkis is an expert on the way monkeys move. He suggested Coldplay try moving like monkeys for their video 'Adventure Of A Lifetime'. The band started to really enjoy themselves, and the story for the video grew out of that.",
        "At the end of a session, we use the computer data to create a moving skeleton. This can be used to create any kind of digital character - a dog, a dragon, or a pirate. For the Coldplay video, we created skeletons of monkeys and then built the bodies of monkeys around the skeletons.",
        "At first we tried using natural-looking monkey faces, but they didn't have enough character. So we created monkey faces that expressed the band members' characters better. It was a fantastic project to work on, and everyone feels proud to have been a part of it!"
    ],
    contentRu: [
        "В наши дни мы почти не задумываемся о «спецэффектах» в фильмах — мы настолько привыкли к ним, что они больше не кажутся нам чем-то особенным! Странный, получеловечный Голлум во «Властелине колец», реалистичный Невероятный Халк и синекожие На'ви в «Аватаре» — все они были созданы в цифровом виде. Но мы верим в них как в реальных персонажей и забываем о технических хитростях. Но как они это делают? Ответ в большинстве случаев — Performance Capture (Захват движений).",
        "Performance Capture — это способ переноса игры реального актера на цифрового персонажа. Актеры могут действовать естественно на цифровой съемочной площадке, и их игра затем «захватывается» камерами и преобразуется в выразительного цифрового героя. Если не задействовать реальных актеров, цифровые персонажи часто кажутся безжизненными и скучными.",
        "Тим Даблдей — специалист по лицам с 12-летним опытом работы в сфере захвата движений. Он работает в ведущей европейской студии Imaginarium в Лондоне, основанной актером Энди Серкисом и Джонатаном Кавендишем. Тим — супервайзер по лицам. Он отвечает за захват мельчайших движений лиц актеров, которые используются для создания реалистичной мимики цифровых героев.",
        "Тим рассказывает историю создания клипа для рок-группы Coldplay. Крис Мартин из Coldplay встретил Энди Серкиса в самолете, и они решили сделать что-то общее. Мы привели участников группы в нашу студию, где вокруг площадки установлено около 50 камер, подключенных к центральному компьютеру.",
        "Все исполнители носят облегающие костюмы со светоотражающими маркерами. Свет от камер отражается от маркеров и фиксируется компьютером, который записывает каждое движение. Лицо исполнителя также покрыто маленькими точками-маркерами, и он носит специальную камеру на голове для захвата малейших изменений мимики.",
        "Энди Серкис — эксперт в том, как двигаются обезьяны. Он предложил Coldplay попробовать двигаться как обезьяны для их клипа «Adventure Of A Lifetime». Группе это действительно понравилось, и из этого выросла целая история для видео.",
        "В конце сессии мы используем компьютерные данные для создания движущегося скелета. Его можно использовать для создания любого цифрового персонажа — собаки, дракона или пирата. Для клипа Coldplay мы создали скелеты обезьян, а затем «нарастили» тела обезьян вокруг этих скелетов.",
        "Сначала мы пробовали использовать натуральные лица обезьян, но им не хватало индивидуальности. Поэтому мы создали лица, которые лучше выражали характеры участников группы. Это был фантастический проект, и мы все гордимся тем, что участвовали в нем!"
    ]
};
